---
title: "Exercise_4-3_Week_7-8"
author: "Tushar Muley"
date: "10/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Libraries
```{r}
library(ggplot2)
library(stringr)
library(dplyr)
library(readr)
library(tidyr)
library(readxl)
```

Load data
```{r}
crimerate <- read_excel('C:/Users/Tushar/Documents/Bellevue_University/DSC_640_Class/Week_7_8/crimerates-by-state-2005.xlsx')
```


Scatter Plot
```{r}
my_plot <- ggplot(crimerate, aes(x = murder, y = burglary)) + 
  geom_point()


my_plot
```

```{r}
my_plot +
  scale_x_continuous(breaks = seq(0, 10, by = 1)) +
  scale_y_continuous(breaks = seq(0, 1500, by = 250)) +
  labs(
    x = 'Murders',
    y = 'Burglary',
    title = 'R Scatter Plot: Murders against burglary'
    )
```


Blubble Chart
```{r}


radius2 <- sqrt( crimerate$population/ pi )
symbols(crimerate$murder, crimerate$burglary, circles=radius2, inches=0.35, fg='white', bg='red', xlab='Murder Rate', ylab='Burglary Rate',
        main = 'R Bubble Chart: Murders against burglary rates') + 
  text(crimerate$murder, crimerate$burglary, crimerate$state, cex=0.5)


```

Density Chart
```{r}

  
plot(crimerate$murder, frame = FALSE, col = "blue",main = "Density plot")

```


```{r}
#Histogram
hist(crimerate$murder, 
     col="green",
     border="black",
     prob = TRUE,
     xlab = "Murder Rate",
     main = "R Density and Histogram Plot: Murder Rate")
#Denisity line
lines(density(crimerate$murder),
      lwd = 2,
      col = "chocolate3")

```

```{r}
# Change line color and fill color
ggplot(crimerate, aes(x=murder))+
  geom_density(color="darkblue", fill="lightblue")+
  labs(
    x = 'Murders Rate',
    y = 'Density',
    title = 'R Density: Murders Rate')

```




